name: Misskey Bot Cron

on:
  schedule:
    - cron: '55 * * * *' # 毎時55分に起動して準備開始
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 最新版に更新

      - name: Set up Python
        uses: actions/setup-python@v5 # 最新版に更新
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install Misskey.py google-generativeai

      - name: Run bot
        env:
          MK_DOMAIN: ${{ secrets.MK_DOMAIN }}
          MK_TOKEN: ${{ secrets.MK_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python bot.py
